# This file was generated by GoReleaser. DO NOT EDIT.
class Tldr < Formula
  desc "Simplified and community-driven man pages"
  homepage "https://github.com/eiladin/tldr"
  version "1.3.4"

  if OS.mac?
    url "https://github.com/eiladin/tldr/releases/download/v1.3.4/tldr_1.3.4_macos_x64.tar.gz"
    sha256 "14fbe367c5428455b4f345037ae77f04f8c4100808ac41f0a066e532c0659dfc"
  elsif OS.linux?
    url "https://github.com/eiladin/tldr/releases/download/v1.3.4/tldr_1.3.4_linux_x64.tar.gz"
    sha256 "edaa9b281bed361e7a0cfa7539d8b0f263f8acf64722fee50a384882f12a2bae"
  end

  def install
    bin.install "tldr"
  end

  test do
    system "#{bin}/tldr --version"
  end
end
